[package]
name = "day6"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
nom = "8.0.0"
test-log = { version = "0.2.19", features = ["trace"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "day6"
harness = false
